before:
  hooks:
    - go mod download
builds:
  - id: build
    flags:
      - -buildmode=exe
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}}
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
  - id: build-macos
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

signs:
  - id: build-macos
    cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    args:
      - "sign-blob"
      - "-key=cosign.key"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: all

archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
