before:
  hooks:
    - go mod download
builds:
  - flags:
      - -buildmode=exe
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}}
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
  - goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on

signs:
  - cmd: cosign
    stdin: '{{ .Secrets.COSIGN_PASSWORD }}'
    env:
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
    args:
      - "sign-blob"
      - "${artifact}"
      - "--yes"
    artifacts: all
archives:
  - name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
