before:
  hooks:
    - go mod download
builds:
  - id: build
    flags:
      - -buildmode=exe
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}}
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
  - id: build-macos
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - COSIGN_PWD={{ .Env.COSIGN_PASSWORD }}
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - sh -c "COSIGN_PASSWORD=$COSIGN_PWD cosign sign-blob --key cosign.key --output-signature dist/{{ .ProjectName }}_{{ .Version }}_{{ .Target }}.sig {{ .Path }}"

archives:
  - id: build-macos
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - dist/*.sig
  - id: build
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
