name: Release
on:
  push:
    tags:
      - 'v*.*.*'
env:
  CGO_ENABLED: 0

jobs:
  release-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.0.5
        with:
          cosign-release: 'v2.0.2'
      - name: Write Key
        run: 'echo "$KEY" > cosign.key'
        env:
          KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        shell: bash
      - name: Build
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
